import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import PDFDocument from "pdfkit";

// =============================================================
// Employee Directory PDF generator
// =============================================================
//
// Builds a professional multi-page PDF directory of all employees,
// grouped by department. Structure:
//   1. Title page (Employee Directory / company / date generated)
//   2. Table of contents (department name -> page number)
//   3. Per-department sections: header + employee table
//   4. Footer on every page: "<page> / <total>" + "Generated by BH HR"
//
// Uses pdfkit (already used elsewhere in /src/lib/document-renderers.ts).
// The TOC page is reserved up-front, then filled in via switchToPage
// after we know each department's starting page.

interface EmployeeRow {
  id: string;
  employeeId: string;
  fullName: string;
  designation?: string | null;
  role?: string | null;
  officialEmail?: string | null;
  phone?: string | null;
  joiningDate?: Date | null;
  photo?: string | null;
  departmentName: string;
  departmentColor?: string | null;
}

interface DeptSection {
  name: string;
  color?: string | null;
  employees: EmployeeRow[];
  startPage: number;
}

function fmtDate(d: Date | null | undefined): string {
  if (!d) return "—";
  const date = d instanceof Date ? d : new Date(d);
  if (isNaN(date.getTime())) return "—";
  return date.toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

// ---- Color helpers (hex without #) ----
const C = {
  primary: "10b981", // emerald-500
  primaryDark: "047857", // emerald-700
  text: "1f2937", // gray-800
  textMuted: "6b7280", // gray-500
  border: "d1d5db", // gray-300
  borderLight: "e5e7eb", // gray-200
  headerBg: "f3f4f6", // gray-100
  rowAlt: "f9fafb", // gray-50
};

// =============================================================
// PDF builder
// =============================================================

async function buildDirectoryPdf(
  sections: DeptSection[],
  company: {
    name: string;
    address?: string | null;
    email?: string | null;
    phone?: string | null;
  } | null,
  totalEmployees: number,
  generatedAt: Date
): Promise<Buffer> {
  return new Promise<Buffer>((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "A4",
        margins: { top: 56, bottom: 64, left: 48, right: 48 },
        bufferPages: true, // required for switchToPage() to reach earlier pages
        info: {
          Title: "Employee Directory",
          Author: "BH HR",
          Subject: "Employee Directory",
        },
      });

      const chunks: Buffer[] = [];
      doc.on("data", (c: Buffer) => chunks.push(c));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      const pageWidth = doc.page.width;
      const pageHeight = doc.page.height;
      const margin = 48;
      const contentWidth = pageWidth - margin * 2;

      // ---- Title page ----
      // Background accent bar at the top
      doc.rect(0, 0, pageWidth, 8).fillColor(C.primary).fill();

      // Large title
      doc
        .fillColor(C.text)
        .font("Helvetica-Bold")
        .fontSize(34);
      doc.text("Employee Directory", margin, pageHeight / 2 - 90, {
        width: contentWidth,
        align: "center",
      });

      // Company name
      doc.font("Helvetica").fontSize(16).fillColor(C.textMuted);
      doc.text(company?.name ?? "BH HR", {
        width: contentWidth,
        align: "center",
      });

      if (company?.address) {
        doc.fontSize(10).text(company.address, {
          width: contentWidth,
          align: "center",
        });
      }
      const contactBits: string[] = [];
      if (company?.email) contactBits.push(company.email);
      if (company?.phone) contactBits.push(company.phone);
      if (contactBits.length > 0) {
        doc.text(contactBits.join("  ·  "), {
          width: contentWidth,
          align: "center",
        });
      }

      // Decorative separator
      const sepY = pageHeight / 2 + 30;
      doc
        .moveTo(margin + 80, sepY)
        .lineTo(pageWidth - margin - 80, sepY)
        .strokeColor(C.primary)
        .lineWidth(1.5)
        .stroke();

      // Generated on / count
      doc.font("Helvetica").fontSize(11).fillColor(C.textMuted);
      doc.text(
        `Generated on ${generatedAt.toLocaleDateString("en-GB", {
          day: "2-digit",
          month: "long",
          year: "numeric",
        })}`,
        { width: contentWidth, align: "center" }
      );
      doc.text(
        `${totalEmployees} employee${totalEmployees === 1 ? "" : "s"} across ${sections.length} department${sections.length === 1 ? "" : "s"}`,
        { width: contentWidth, align: "center" }
      );

      // ---- Table of contents page ----
      doc.addPage();
      doc.x = margin;
      doc.y = margin + 8;
      doc
        .font("Helvetica-Bold")
        .fontSize(20)
        .fillColor(C.text)
        .text("Table of Contents", { align: "left" });

      // underline
      const tocUnderlineY = doc.y + 2;
      doc
        .moveTo(margin, tocUnderlineY)
        .lineTo(margin + 200, tocUnderlineY)
        .strokeColor(C.primary)
        .lineWidth(1.5)
        .stroke();

      doc.moveDown(1.2);
      doc.font("Helvetica").fontSize(11).fillColor(C.textMuted);
      doc.text(
        "Department sections are listed below with their starting page number.",
        { width: contentWidth }
      );
      doc.moveDown(1.5);

      // We'll fill in the page numbers AFTER rendering the sections
      // (we don't know them yet). For now, just lay out the department
      // names + color swatches so the TOC is visually complete; the page
      // number column stays blank until the backfill pass.
      const tocEntriesStartY = doc.y;
      sections.forEach((s, idx) => {
        const y = tocEntriesStartY + idx * 22;
        // Color swatch
        doc.rect(margin, y + 4, 6, 6).fillColor(s.color || C.primary).fill();
        // Dept name
        doc
          .font("Helvetica-Bold")
          .fontSize(11)
          .fillColor(C.text)
          .text(s.name, margin + 14, y, {
            width: contentWidth - 100,
            continued: false,
          });
        // Dotted leader line (visual aid connecting name to page number)
        doc.font("Helvetica-Bold").fontSize(11);
        const nameWidth = doc.widthOfString(s.name);
        const leaderStartX = margin + 14 + nameWidth + 6;
        const leaderEndX = pageWidth - margin - 50;
        if (leaderEndX > leaderStartX) {
          doc
            .dash(1, { space: 2 })
            .moveTo(leaderStartX, y + 8)
            .lineTo(leaderEndX, y + 8)
            .strokeColor(C.border)
            .lineWidth(0.5)
            .stroke()
            .undash();
        }
        // Employee count subtitle on the next line
        doc
          .font("Helvetica")
          .fontSize(9)
          .fillColor(C.textMuted)
          .text(
            `${s.employees.length} employee${s.employees.length === 1 ? "" : "s"}`,
            margin + 14,
            y + 13,
            { width: contentWidth - 100 }
          );
      });

      // ---- Per-department sections ----
      sections.forEach((section) => {
        doc.addPage();
        // doc.bufferedPageRange().count is the current 1-indexed page number.
        section.startPage = doc.bufferedPageRange().count;

        // Section header band
        const headerY = margin;
        doc
          .rect(margin, headerY, contentWidth, 36)
          .fillColor(section.color || C.primary)
          .fill();
        doc
          .font("Helvetica-Bold")
          .fontSize(16)
          .fillColor("ffffff")
          .text(section.name, margin + 12, headerY + 9, {
            width: contentWidth - 24,
          });
        doc
          .font("Helvetica")
          .fontSize(9)
          .fillColor("ffffff")
          .opacity(0.85)
          .text(
            `${section.employees.length} employee${section.employees.length === 1 ? "" : "s"}`,
            margin + 12,
            headerY + 23,
            { width: contentWidth - 24 }
          );
        doc.opacity(1);

        // Table header
        const tableTop = headerY + 50;
        const colWidths = {
          photo: 36,
          name: 130,
          empId: 60,
          designation: 110,
          email: 110,
          phone: 70,
          joining: 60,
        };
        // Scale columns to fit contentWidth
        const totalCol = Object.values(colWidths).reduce((a, b) => a + b, 0);
        const scale = contentWidth / totalCol;
        const scaledCols = {
          photo: colWidths.photo * scale,
          name: colWidths.name * scale,
          empId: colWidths.empId * scale,
          designation: colWidths.designation * scale,
          email: colWidths.email * scale,
          phone: colWidths.phone * scale,
          joining: colWidths.joining * scale,
        };

        const headerRowHeight = 22;
        let x = margin;
        const drawHeaderCell = (label: string, w: number) => {
          doc
            .rect(x, tableTop, w, headerRowHeight)
            .fillColor(C.headerBg)
            .fill();
          doc
            .strokeColor(C.borderLight)
            .lineWidth(0.5)
            .rect(x, tableTop, w, headerRowHeight)
            .stroke();
          doc
            .font("Helvetica-Bold")
            .fontSize(8.5)
            .fillColor(C.text)
            .text(label, x + 4, tableTop + 7, {
              width: w - 8,
              height: headerRowHeight - 8,
            });
          x += w;
        };
        // First column header is empty (photo column)
        drawHeaderCell("", scaledCols.photo);
        drawHeaderCell("Name", scaledCols.name);
        drawHeaderCell("Emp ID", scaledCols.empId);
        drawHeaderCell("Designation", scaledCols.designation);
        drawHeaderCell("Email", scaledCols.email);
        drawHeaderCell("Phone", scaledCols.phone);
        drawHeaderCell("Joined", scaledCols.joining);

        // Body rows
        const rowHeight = 28;
        let rowY = tableTop + headerRowHeight;
        const rowCap = (idx: number) => idx % 2 === 1;

        const drawTableHeader = (topY: number, continuedLabel?: string) => {
          if (continuedLabel) {
            doc
              .rect(margin, topY - 30, contentWidth, 22)
              .fillColor(section.color || C.primary)
              .fill();
            doc
              .font("Helvetica-Bold")
              .fontSize(10)
              .fillColor("ffffff")
              .text(continuedLabel, margin + 10, topY - 24, {
                width: contentWidth - 20,
              });
          }
          let hx = margin;
          const drawHCell = (label: string, w: number) => {
            doc
              .rect(hx, topY, w, headerRowHeight)
              .fillColor(C.headerBg)
              .fill();
            doc
              .strokeColor(C.borderLight)
              .lineWidth(0.5)
              .rect(hx, topY, w, headerRowHeight)
              .stroke();
            doc
              .font("Helvetica-Bold")
              .fontSize(8.5)
              .fillColor(C.text)
              .text(label, hx + 4, topY + 7, {
                width: w - 8,
                height: headerRowHeight - 8,
              });
            hx += w;
          };
          drawHCell("", scaledCols.photo);
          drawHCell("Name", scaledCols.name);
          drawHCell("Emp ID", scaledCols.empId);
          drawHCell("Designation", scaledCols.designation);
          drawHCell("Email", scaledCols.email);
          drawHCell("Phone", scaledCols.phone);
          drawHCell("Joined", scaledCols.joining);
        };

        section.employees.forEach((emp, idx) => {
          // Page-break if needed
          if (rowY + rowHeight > pageHeight - 80) {
            doc.addPage();
            // Repeat section header band (compact) + table header on new page
            rowY = margin + 30;
            drawTableHeader(rowY, `${section.name} (continued)`);
            rowY = rowY + headerRowHeight;
          }

          // Row background (alt)
          if (rowCap(idx)) {
            doc
              .rect(margin, rowY, contentWidth, rowHeight)
              .fillColor(C.rowAlt)
              .fill();
          }
          // Cell borders
          x = margin;
          const drawBodyCell = (
            text: string,
            w: number,
            opts: { font?: string; size?: number; color?: string } = {}
          ) => {
            doc
              .strokeColor(C.borderLight)
              .lineWidth(0.5)
              .rect(x, rowY, w, rowHeight)
              .stroke();
            doc
              .font(opts.font || "Helvetica")
              .fontSize(opts.size || 8.5)
              .fillColor(opts.color || C.text)
              .text(text, x + 4, rowY + 9, {
                width: w - 8,
                height: rowHeight - 12,
                ellipsis: true,
              });
            x += w;
          };

          // Photo placeholder (circle with initials)
          doc
            .strokeColor(C.borderLight)
            .lineWidth(0.5)
            .rect(x, rowY, scaledCols.photo, rowHeight)
            .stroke();
          const initials = emp.fullName
            .split(/\s+/)
            .map((p) => p[0])
            .slice(0, 2)
            .join("")
            .toUpperCase();
          doc
            .circle(x + scaledCols.photo / 2, rowY + rowHeight / 2, 9)
            .fillColor(section.color || C.primary)
            .fill();
          doc
            .font("Helvetica-Bold")
            .fontSize(7)
            .fillColor("ffffff")
            .text(initials, x, rowY + rowHeight / 2 - 4, {
              width: scaledCols.photo,
              align: "center",
            });
          x += scaledCols.photo;

          drawBodyCell(emp.fullName || "—", scaledCols.name, {
            font: "Helvetica-Bold",
            size: 9,
          });
          drawBodyCell(emp.employeeId || "—", scaledCols.empId, { size: 8 });
          drawBodyCell(emp.designation || "—", scaledCols.designation);
          drawBodyCell(emp.officialEmail || "—", scaledCols.email, {
            size: 7.5,
          });
          drawBodyCell(emp.phone || "—", scaledCols.phone, { size: 8 });
          drawBodyCell(fmtDate(emp.joiningDate), scaledCols.joining, {
            size: 7.5,
          });

          rowY += rowHeight;
        });

        // End-of-section summary
        rowY += 8;
        if (rowY + 20 < pageHeight - 80) {
          doc
            .font("Helvetica-Oblique")
            .fontSize(9)
            .fillColor(C.textMuted)
            .text(
              `End of ${section.name} — ${section.employees.length} employee${section.employees.length === 1 ? "" : "s"} listed.`,
              margin,
              rowY,
              { width: contentWidth }
            );
        }
      });

      // ---- Total page count ----
      const range = doc.bufferedPageRange();
      const total = range.count;

      // ---- Fill in the TOC page numbers ----
      // The TOC lives on page index 1 (0-indexed). Section startPage values
      // are 1-indexed absolute page numbers, so we just write them directly.
      doc.switchToPage(1); // TOC page
      // Write the real page number for each section entry. We left the
      // page-number column blank during the initial TOC render, so there's
      // nothing to clear — we just write on top.
      let tocY = tocEntriesStartY;
      sections.forEach((s) => {
        doc
          .font("Helvetica-Bold")
          .fontSize(11)
          .fillColor(C.primaryDark)
          .text(String(s.startPage), pageWidth - margin - 40, tocY, {
            width: 40,
            align: "right",
          });
        tocY += 22;
      });

      // ---- Footers on every page ----
      for (let i = 0; i < total; i++) {
        doc.switchToPage(i);
        // Skip the title page footer (page 0) — it has its own design.
        if (i === 0) continue;
        const footerY = pageHeight - 36;
        doc
          .moveTo(margin, footerY)
          .lineTo(pageWidth - margin, footerY)
          .strokeColor(C.borderLight)
          .lineWidth(0.5)
          .stroke();
        doc
          .font("Helvetica")
          .fontSize(8)
          .fillColor(C.textMuted)
          .text("Generated by BH HR", margin, footerY + 6, {
            width: contentWidth / 2,
            align: "left",
          });
        doc.text(`Page ${i + 1} of ${total}`, pageWidth / 2, footerY + 6, {
          width: contentWidth / 2,
          align: "right",
        });
      }

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

// =============================================================
// Route handler
// =============================================================

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const departmentId = searchParams.get("departmentId") || "";
  const status = searchParams.get("status") || "";

  const where: any = {};
  if (departmentId) where.departmentId = departmentId;
  if (status) where.employmentStatus = status;

  // Fetch employees + company in parallel
  const [employees, company] = await Promise.all([
    db.employee.findMany({
      where,
      include: {
        department: true,
        role: true,
        designation: true,
      },
      orderBy: [{ department: { name: "asc" } }, { employeeId: "asc" }],
    }),
    db.company.findFirst({ orderBy: { createdAt: "asc" } }),
  ]);

  // Group employees by department
  const sectionMap = new Map<string, DeptSection>();
  const unknownKey = "— No Department —";
  for (const emp of employees) {
    const deptName = emp.department?.name ?? unknownKey;
    if (!sectionMap.has(deptName)) {
      sectionMap.set(deptName, {
        name: deptName,
        color: emp.department?.color ?? null,
        employees: [],
        startPage: 0,
      });
    }
    sectionMap.get(deptName)!.employees.push({
      id: emp.id,
      employeeId: emp.employeeId,
      fullName: emp.fullName,
      designation: emp.designation?.name ?? null,
      role: emp.role?.name ?? null,
      officialEmail: emp.officialEmail ?? null,
      phone: emp.phone ?? null,
      joiningDate: emp.joiningDate ?? null,
      photo: emp.photo ?? null,
      departmentName: deptName,
      departmentColor: emp.department?.color ?? null,
    });
  }

  const sections = Array.from(sectionMap.values()).sort((a, b) =>
    a.name.localeCompare(b.name)
  );

  const generatedAt = new Date();
  const pdfBuffer = await buildDirectoryPdf(
    sections,
    company
      ? {
          name: company.name,
          address: company.address,
          email: company.email,
          phone: company.phone,
        }
      : null,
    employees.length,
    generatedAt
  );

  // Audit log (non-fatal)
  try {
    await db.auditLog.create({
      data: {
        action: "EMPLOYEE_DIRECTORY_PDF",
        entityType: "Employee",
        description: `Generated employee directory PDF (${employees.length} employees, ${sections.length} departments)`,
      },
    });
  } catch {
    // ignore
  }

  const dateStr = generatedAt.toISOString().split("T")[0];
  return new NextResponse(pdfBuffer as any, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="employee-directory-${dateStr}.pdf"`,
      "Cache-Control": "no-store",
    },
  });
}
